### ISSUE TITLE
[feature request] Open files that are not linked to a default app

### ISSUE THREAD

**Issue by danielmmmm** [DF1E/SimpleExplorer#31]
"Unknown" files cannot be opened with SE, it simply displays a toast saying "Cannot open this file". It would be helpful, if SE could let the user choose which app to open a file with (=> list of all apps). Even better would be a dialogue that lets the user choose as what kind of file a file should be opened as. This way, the list of possible apps to choose from would be shorter.

Example:
I want to open "script.sh" and click onto the file
=> SE asks me as what file type I would like to open script.sh.
I choose "open as text file"
=> SE shows a list of all apps that can open text files.

**Comment by DF1E** [comment]
Please try the following apk and report if it works now..
https://www.dropbox.com/s/xrw8auggz2efgb7/Simple%20Explorer%20-%20test.apk?dl=0

**Comment by danielmmmm** [comment]
This version behaves the same unfortunately. I see that it uses the view intent, but nothing more happens. My system is heavily restricted by XPrivacy, but I have allowed everything for SE. Apart from that, all other apps seem to not have any problems opening files (in other apps).

**Comment by DF1E** [comment]
Maybe it depends on your system because I can open files with every app I want..

**Comment by danielmmmm** [comment]
Yes, then it must be my system. Thank you for testing! I will try to find out what's wrong on my phone.

**Comment by danielmmmm** [comment]
I think I know what the problem is. The scripts are located in /system/addon.d and apparently, SE does not have access to them. When I want to copy or move them, I see an SELinux error in my LogCat (Could not open /data/system/ packages list: Permission denied.). Root is activated in the settings.

This actually brings us to another problem: Whenever SE fails to perform an operation (like failing to copy a file due to permission denial) it still displays a toast saying that the operation was completed successfully.
I also noticed that I sometimes can mark scripts in /system/addon.d by long-clicking and sometimes long-clicking fails with an SE toast "Cannot open file".

**Comment by DF1E** [comment]
Yeah, I think there are only problems with SELinux because in other directories deleting with root works fine. I will close this issue and open a new one. Thanks for reporting!
