### ISSUE TITLE
Frequent Crashes

### ISSUE THREAD

**Issue by maysleazy** [DF1E/SimpleExplorer#34]
Crashes a lot after giving root permissions on xhdpi devices. Tried on various emulators.
Suggest to implement libraries from here - https://github.com/kshark27/UltraExplorer
Will update issue after trying to fix this bug. Supporting as much as possible
thanks for this awesome File Explorer :) :+1:

**Comment by DF1E** [comment]
Thanks for reporting! I dont think the crashes are depending on the libraries because I've no problems with them. To solve this problem I have some questions:
- Do you have crashes only if you enable root?
- Are there certain steps to reproduce the crashes?

**Comment by maysleazy** [comment]
• Yes, only with root enabled.
• No, random crashes. Occurs whenever it wants to. Sometimes while starting the app.
Diagnosis - 
1. Tried clearing app cache and data and gave root access again, doesn't help much.
2. Happens only on a few devices. Especially with custom Roms, tried on CM12 and PA, both had crashes.
3. Will attach a log when i'm free later today.

Also, can you add a permission setting for root files? I can access them but I don't seem to have the option to set the permissions on them.
Thanks for co-operation :+1: :)

**Comment by maysleazy** [comment]
Also, folders are deleted with root.

**Comment by DF1E** [comment]
There is a bug in permission dialog, sometimes you cant change them. I will fix that issue soon..
