### ISSUE TITLE
"Empty" root folders

### ISSUE THREAD

**Issue by maysleazy** [DF1E/SimpleExplorer#35]
Root folders are shown as "empty" even after giving them root permissions. I'm pretty sure they are not empty.
EDIT: Screenshots from one of my friends phones.
![img-20150303-wa0005](https://cloud.githubusercontent.com/assets/11243138/6458015/9c44321e-c1a4-11e4-9756-5aef43ba03e7.jpg)

**Comment by DF1E** [comment]
The folder "/root" is simply empty. I tested it on my phone too with different file explorer. You can try to open "/data" folder and it should work..

**Comment by maysleazy** [comment]
Yeah, sorry, I forgot to update the comment after I found it out earlier today.
