### ISSUE TITLE
Feature Requests : Sqlite DB browser and editing, cleanup of unnecessary odex files and masss apps zipalign

### ISSUE THREAD

**Issue by Immortalin** [DF1E/SimpleExplorer#37]
Hi, I came across your browser while looking for an alternative to [this](http://forum.xda-developers.com/showthread.php?t=1338582) as the author stopped development on it. Looks really good, may I include it in my rom? I have a list of feature request that you may want to consider adding to the todo. Thanks in advance for your hard work!

**Comment by davidcie** [comment]
From my point of view adding an sqlite browser is a few steps on a path away from the simplicity I love Simple Explorer for.
