### ISSUE TITLE
2.2.5 F-droid ver. // Force crash at start

### ISSUE THREAD

**Issue by JoshGraham** [DF1E/SimpleExplorer#38]
- Description : At 2.2.4 ver, sometimes it crashed at start. Didn't report, my bad. At 2.2.5 ver, everytime trying to open the app, it crashes.
- Expected behavior : Open app
- Actual behavior : Force crashes.

logfile
https://gist.githubusercontent.com/JoshGraham/e8986d349e228f6732e7/raw/34bfa226735e99d1fc9c655e6c5d60c82030da28/gistfile1.txt

**Comment by DF1E** [comment]
please try to delete the old version and make a clean install..

**Comment by JoshGraham** [comment]
Aw, that fixed it.
Thanks.
