### ISSUE TITLE
2.2.5 F-droid ver. // White shading at top

### ISSUE THREAD

**Issue by JoshGraham** [DF1E/SimpleExplorer#39]
- Description
This bug wasn't present before.
At white theme, no bug.[1]
At dark theme, when long-press-folder, top bar goes white, thus can't see icons to tap.[2]
Icons are fuctional and threre, just can't see icons.
After tapping 'invisible' icon, it goes back to normal and visible.[3]

- logfile
https://gist.githubusercontent.com/JoshGraham/91bb721ae2c1eb3c032b/raw/ad6c2f462a13410684050fd3a9400fcf16cf36f9/gistfile1.txt

- screenshot
[1] white theme
![white](https://cloud.githubusercontent.com/assets/8502832/6895364/55674b7a-d71a-11e4-8954-907814a1601e.png)

[2] dark theme - invisible
![invisible](https://cloud.githubusercontent.com/assets/8502832/6895375/707fe73c-d71a-11e4-8f4e-a5a02ea18e00.png)

[3] dark theme - visible again
![visible-again](https://cloud.githubusercontent.com/assets/8502832/6895379/7c8ff026-d71a-11e4-901f-cb06c840c098.png)

Thanks
Josh

**Comment by DF1E** [comment]
Do you use stock rom?

**Comment by JoshGraham** [comment]
On 03/30/2015 09:47 PM, DF1E wrote:
>
> Do you use stock rom?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DF1E/SimpleExplorer/issues/39#issuecomment-87664340>.
>
Yes, but it's heavily customized.

Please close if it's due to user misconfiguration, thus not app's bug.

Josh

**Comment by JoshGraham** [comment]
Tried another phone with stock rom.
Icon shows up when long-pressed, though it's white-on-white.

- Additional screenshot
![3](https://cloud.githubusercontent.com/assets/8502832/6912639/639ee712-d7af-11e4-8d6d-cdf3e7eb2c44.png)

![4](https://cloud.githubusercontent.com/assets/8502832/6912641/673ef02e-d7af-11e4-990f-d1e7a8e46dfb.png)

**Comment by DF1E** [comment]
Strange.. there is also a second report on xda (http://forum.xda-developers.com/showpost.php?p=59577015&postcount=382)
I will look for that issue..

**Comment by unrulygnu** [comment]
This seems to have been due to a pre-Lollipop theming bug in `appcompat-v7:22.0+`.

![android4-2 2 5-dark-actionmode-allwhite](https://cloud.githubusercontent.com/assets/11031903/7556014/d48b363c-f79a-11e4-843f-96c43bcebade.png)

@DF1E upgraded to the recently released `appcompat-v7:22.1.1` in `master`, which seems to fix this issue.

![android4-head-dark-actionmode-fixed](https://cloud.githubusercontent.com/assets/11031903/7556027/4da0273a-f79b-11e4-9bd5-2e1014d4e543.png)

**Comment by DF1E** [comment]
unrulygnu is right, the problem was in appcompat library. The fix will be in the next release
