### ISSUE TITLE
Feature: Enable other apps to browse and choose files via implicit Intent

### ISSUE THREAD

**Issue by unrulygnu** [DF1E/SimpleExplorer#45]
**Desired behavior**

1. In a third-party app, initiate "Choose file" (or similar action)
2. Third-party app sends an implicit `Intent` (`ACTION_GET_CONTENT`)
3. System displays a `DocumentsActivity` (KitKat or later) or `ResolverActivity` (pre-KitKat) with SimpleExplorer presented as an option
4. Select SimpleExplorer
5. System starts "Choose a file" `Activity` in SimpleExplorer
6. Browse and choose a file in SimpleExplorer (allow multiple selections if `EXTRA_ALLOW_MULTIPLE` included, api 18 `JELLY_BEAN_MR2` and above)
7. System restarts third-party app `Activity` with chosen file `Uri` in `Intent`

**Implementation**

Implementing this feature shouldn't impact performance at all, nor should it require any additional permissions, and it should reuse existing components with only minor updates.  

@DF1E, if you don't have any objections, I'll start working on this in the next couple of days.  If it looks like it will require more significant changes than anticipated, I'll post here.

**Comment by DF1E** [comment]
merged
