### ISSUE TITLE
Copying from internal storage to external (microSDXC card) fails

### ISSUE THREAD

**Issue by mary-kate** [DF1E/SimpleExplorer#58]
I sent a file from another device to my Fonepad over Bluetooth; the file was placed in `/storage/emulated/0/bluetooth/`, which appears to be Fonepad's default directory where to place files received over Bluetooth. Attempting to copy this file into `/storage/MicroSD/DCIM/` de facto fails, though SimpleExplorer claims that it was copied successfully (the `copysuccsess` internationalization message). Copying the same file with the Fonepad's built-in file manager works as it shows up in the directory right away, as you'd expect.

Device: Asus Fonepad 7 (ME372CG), rooted
OS: KitKat (4.4.2)
SimpleExplorer version: 2.2.5 (root access enabled in app settings)

**Comment by DF1E** [comment]
This is a known issue. Currently there is no external sdcard support for kitkat devices and up..
