### ISSUE TITLE
Cannot move file to Real External SD card

### ISSUE THREAD

**Issue by giaotuancse** [DF1E/SimpleExplorer#84]
I cannot cut/copy a file from storage of Phone to real external SD card (with phone support external sd card). Also cannot create a file/folder in real external SD card
Tested with version 2.3.1

**Comment by mkaito** [comment]
Just came across this issue. Installed a microSD card on my phone, files disappeared silently when trying to move them from internal to external storage. Could not create folders either. Phone is rooted and SE is running as root.
